<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuariosSeeder extends Seeder
{
    public function run()
    {
        // Insertar usuarios existentes
        DB::table('usuarios')->insert([
            [
                'usr_id' => 1,
                'usr_username' => 'admin_user',
                'usr_password' => Hash::make('password123'),
                'usr_nombre_completo' => 'Juan Pérez',
                'usr_correo_electronico' => 'juan.perez@example.com',
                'usr_telefono' => '5551234567',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 1,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-09 10:00:00',
            ],
            [
                'usr_id' => 2,
                'usr_username' => 'barber_joe',
                'usr_password' => Hash::make('password456'),
                'usr_nombre_completo' => 'José López',
                'usr_correo_electronico' => 'jose.lopez@example.com',
                'usr_telefono' => '5559876543',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 2,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-09 11:00:00',
            ],
            [
                'usr_id' => 3,
                'usr_username' => 'facialist_anna',
                'usr_password' => Hash::make('password789'),
                'usr_nombre_completo' => 'Ana García',
                'usr_correo_electronico' => 'ana.garcia@example.com',
                'usr_telefono' => '5554567890',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 3,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-09 12:00:00',
            ],
            [
                'usr_id' => 4,
                'usr_username' => 'reception_lucy',
                'usr_password' => Hash::make('password321'),
                'usr_nombre_completo' => 'Lucía Ramírez',
                'usr_correo_electronico' => 'lucia.ramirez@example.com',
                'usr_telefono' => '5556543210',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 2,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-09 13:00:00',
            ],
            [
                'usr_id' => 5,
                'usr_username' => 'client_john',
                'usr_password' => Hash::make('password654'),
                'usr_nombre_completo' => 'John Doe',
                'usr_correo_electronico' => 'john.doe@example.com',
                'usr_telefono' => '5551122334',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 3,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-09 14:00:00',
            ],
            [
                'usr_id' => 6,
                'usr_username' => 'client_maria',
                'usr_password' => Hash::make('password111'),
                'usr_nombre_completo' => 'María Fernández',
                'usr_correo_electronico' => 'maria.fernandez@example.com',
                'usr_telefono' => '5552233445',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 4,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-10 09:00:00',
            ],
            [
                'usr_id' => 7,
                'usr_username' => 'client_pedro',
                'usr_password' => Hash::make('password222'),
                'usr_nombre_completo' => 'Pedro Martínez',
                'usr_correo_electronico' => 'pedro.martinez@example.com',
                'usr_telefono' => '5553344556',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 4,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-10 10:00:00',
            ],
            [
                'usr_id' => 8,
                'usr_username' => 'client_lucia',
                'usr_password' => Hash::make('password333'),
                'usr_nombre_completo' => 'Lucía Gómez',
                'usr_correo_electronico' => 'lucia.gomez@example.com',
                'usr_telefono' => '5554455667',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 4,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-10 11:00:00',
            ],
            [
                'usr_id' => 9,
                'usr_username' => 'client_carlos',
                'usr_password' => Hash::make('password444'),
                'usr_nombre_completo' => 'Carlos Sánchez',
                'usr_correo_electronico' => 'carlos.sanchez@example.com',
                'usr_telefono' => '5555566778',
                'usr_foto_perfil' => null,
                'usr_activo' => true,
                'usr_rol_id' => 4,
                'usr_recuperacion_token' => null,
                'usr_recuperacion_expira' => null,
                'usr_ultimo_acceso' => '2024-11-10 12:00:00',
            ],
        ]);

    }
}
